name: "Executar meu script"
on:
  issues:
    types: [opened]

jobs:
  meu_script:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Print issue details"
        run: |
          echo '${{ toJson(github.event.issue) }}'
      - name: "Print some variables"
        run: |
          echo '${{ vars.TESTE_VAR }}'
          echo '${{ variables.TESTE_VAR }}'
          echo '${{ secrets.TESTE_VAR }}'
          echo '${{ env.TESTE_VAR }}'

