name: "Executar meu script"
on:
  issues:
    types: [opened]
jobs:
  meu_script:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Setup Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.x"
      - name: "Print custom JSON"
        run: |
          python -c "
          import json
          import os
          
          data = {
            'list': os.getenv('CLICKUP_LIST_ID'),
            'name': f'{os.getenv('ISSUE_TITLE')} #{os.getenv('ISSUE_NUMBER')}',
            'markdown_description': os.getenv('ISSUE_BODY'),
            'tags': json.loads(os.getenv('ISSUE_LABELS')),
            'status': 'Open',
            'notify_all': True,
            'priority': 3,
            'assignees': os.getenv('CLICKUP_ASSIGNESS_LIST')
          }

          get_priority = lambda tags: (lambda lower_tags: 1 if 'urgent' in lower_tags else 2 if 'high' in lower_tags else 3 if 'normal' in lower_tags else 4)(map(lambda x: x.lower(),tags))
          data['priority'] = get_priority(data['tags'])
          
          print(json.dumps(data, indent=2))
          "
            
        env:
          CLICKUP_LIST_ID: ${{ vars.CLICKUP_LIST_ID }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_LABELS: ${{ toJson(github.event.issue.labels.*.name) }}
          CLICKUP_ASSIGNESS_LIST: ${{ vars.CLICKUP_ASSIGNESS_LIST }}
