name: "Executar meu script"
on:
  issues:
    types: [opened]

jobs:
  meu_script:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "Print issue details"
        run: |
          echo "Teste de string"
      # - name: "Print custom JSON"
      #   run: |
      #     JSON_STRING='{
      #       "list": "${{ vars.CLICKUP_LIST_ID }}",
      #       "name": "${{ github.event.issue.title }} #${{ github.event.issue.number }}",
      #       "markdown_description": "${{ github.event.issue.body }}",
      #       "tags": "${{ toJson(github.event.issue.labels.*.name) }}",
      #       "status": "Open",
      #       "notify_all": true,
      #       "priority": 3,
      #       "assignees": "${{ vars.CLICKUP_ASSIGNESS_LIST }}"
      #     }'
      #     echo $JSON_STRING
