name: "Create Issue from TODO"
on: ["push"]
jobs:
  pre:
    runs-on: "ubuntu-latest"
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build:
    needs: pre
    if: ${{ needs.pre.outputs.should_skip == 'false' }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v4"
